plugins:
  - jekyll-seo-tag
title: "Ahmed's Data Science Portfolio 🚀"
description: "Explore my journey as a Data Scientist, showcasing projects in Data Science and Machine Learning."
url: "https://ahmadalharbi21.github.io/portfolio"
theme: null
